### ISSUE TITLE
Fixes for README.md

### ISSUE THREAD

**Issue by abias** [moodlehq/moodle-php-apache#10]
Hi Dan,

I just started working with this tool and have some fixes for README.md:
* On https://github.com/moodlehq/moodle-php-apache#see-also, the link to docker-moodle should go to https://github.com/moodlehq/moodle-docker and be labeled "moodle-docker"

Thanks,
Alex

**Comment by danpoltawski** [comment]
Thanks Alex, this is a regression from https://github.com/moodlehq/moodle-docker/issues/16 

I will fix this shortly, but if you want to do a pull request, i'll be happy to merge this too.

**Comment by abias** [comment]
Done. I lazily edited the files in Github directly.

**Comment by danpoltawski** [comment]
Fixed by #11
