### ISSUE TITLE
moodlehq:7.4 course management

### ISSUE THREAD

**Issue by acmodeu** [moodlehq/moodle-php-apache#106]
Hi.

I stumbled upon the problem with course backup and deletion on moodlehq:7.4.

On backup operation the page fails to load and the following record appears in php log:
`[core:notice] [pid 1] AH00052: child pid 19 exit signal Segmentation fault (11)`

On delete operation site page fails to load and the following record appears in php log:
`[core:notice] [pid 1] AH00052: child pid 23 exit signal Segmentation fault (11)`

Reverting back to moodlehq:7.3 instantly solved my problems.

**Comment by scara** [comment]
Hi @acmodeu,
do you mean related tests are failing or that you're using the image to run your Moodle instance into "production"?

Which version of Moodle are you running with this image?

TIA;
Matteo

**Comment by acmodeu** [comment]
Hi @scara,

Yes, we are using our Moodle instance into production. We are using its so far latest build 3.8.1 (20200113)

**Comment by stronk7** [comment]
Hi @acmodeu,

> PHP 7.4 support is being implemented (MDL-66260) for Moodle 3.8.x and later releases. Hence it's still incomplete and only for development purposes
Source: https://docs.moodle.org/dev/Moodle_and_PHP7

Ciao :-)
