### ISSUE TITLE
error when it's running

### ISSUE THREAD

**Issue by legendofmiracles** [moodlehq/moodle-php-apache#125]
```
Fatal error: Method lang_string::__set_state() must take exactly 1 argument in /var/www/html/lib/moodlelib.php on line 10664
```
It doesn't matter what i open.. install.php, nothing etc..
I didn't change a single line in the moodle source code, just doing this to test something.

Any ideas?

**Comment by scara** [comment]
Hi @legendofmiracles,
you should post your support request for free in https://moodle.org/mod/forum/view.php?id=28.

That being said, you should provide info about:
1. which version of Moodle code you're trying to use
2. which version i.e. tag of the `moodle-php-apache` image you're trying to run

It looks like you're playing with PHP 8 i.e. tag `8.0` using a Moodle version not ready for that.
The Moodle vs PHP compat matrix is available [here](https://docs.moodle.org/dev/Moodle_and_PHP).

HTH,
Matteo

**Comment by legendofmiracles** [comment]
Using an older veresion of PHP worked. Thanks!
