### ISSUE TITLE
Docs don't explain how to use!

### ISSUE THREAD

**Issue by cliffbdf** [moodlehq/moodle-php-apache#130]
Ran the image and also the moodlehq/moodle-db-oracle-r2 image, ports mapped, volume mapped, but I get a "403 Forbidden" when trying to access port 8080. Is there a config file that needs to be set in the current directory?

**Comment by scara** [comment]
Hi @cliffbdf,
you should follow the docs in https://github.com/moodlehq/moodle-docker#quick-start.
FYI the image here is just the web server including the PHP stack ready for Moodle, w/o any Moodle core code.

HTH,
Matteo

**Comment by cliffbdf** [comment]
Thank you!
