### ISSUE TITLE
Add PHP 8.1 images

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-php-apache#135]
This issue is to track adding PHP 8.1 images. At the time of creating this, that version is still under development and will be released later (December 2021).

Till then we'll be building rc/beta images to monitor what's breaking/missing and, also to enable various tests and checks to be performed in advance.

Ongoing work happening @ https://github.com/moodlehq/moodle-php-apache/compare/8.0-buster...stronk7:8.1-buster

**Comment by stronk7** [comment]
Ok, 8.1beta3 has been just sent to dockerhub (amd64 only): [moodlehq/moodle-php-apache:8.1beta3](https://hub.docker.com/layers/moodlehq/moodle-php-apache/8.1beta3/images/sha256-e5639326e0d9e137a7a560a32709cfcab0e06926ac425e654aedc9509a9bdd3b?context=repo)

Not working (not available yet):
- mongodb extension.
- xmlrpc extension.
- sqlsrv extension.

Surprisingly good for the very first run, let's see how they evolve.

Ciao :-)

**Comment by scara** [comment]
Hi Eloy,
it's worth looking at https://blog.remirepo.net/pages/PECL-extensions-RPM-status (PHP 8.1 as [SCL](https://www.softwarecollections.org/) for RedHat-ish OSs), to get the feeling of the current status from Remi who is still working hard on PHP extensions e.g. `mongodb` looks like [already](https://github.com/mongodb/mongo-php-driver/pull/1240) available for [Remi's PHP 8.1 SCL](https://github.com/remicollet/remirepo/issues/177#issuecomment-885038520)  so there would be a chance to get it into the Debian repos too.

Whilst for the others:
- `sqlsrv`, you're right: https://docs.microsoft.com/en-us/sql/connect/php/system-requirements-for-the-php-sql-driver?redirectedfrom=MSDN&view=sql-server-ver15. It looks ["almost there"](https://github.com/microsoft/msphpsql/issues/1230#issuecomment-871542317) in [branch `dev`](https://github.com/microsoft/msphpsql/commit/5e607a802c5e0376325c6b1e8a5dc62dffa24f95), even with [updated tests](https://github.com/microsoft/msphpsql/pull/1285/files#diff-edbdf0cf230845f74dc7c6bf477bb4cc2292b06be2782a38c7f331a02698555b)
- `xmlrpc`, looks like now available, still deprecated, from PECL

HTH,
Matteo

**Comment by stronk7** [comment]
Yeah,

I tried building here both with `mongodb` and `xmlrpc`(beta @ PECL) but both failed (with similar compilation errors, from memory).

And yes, sqlsrv seems to be near, I did read that their next "beta" release was going to include it, cool.

Thanks for your research!

**Comment by stronk7** [comment]
Have bumped the image to 8.1 rc2: [moodlehq/moodle-php-apache:8.1rc2](https://hub.docker.com/r/moodlehq/moodle-php-apache/tags?page=1&ordering=last_updated)

sqlsrv support added. mongodb and xmlrpc still not working.

**Comment by stronk7** [comment]
Note I bumped to 8.1 rc5 few days ago, but I did not look to any of:
- Final / better sqlsrv version.
- mongodb
- xmlrpc
- 
Will try whenever I have a few time...

**Comment by stronk7** [comment]
Bumping to rc6:

- sqlsrv (5.10.0beta1), for debian 10 (buster), previously using debian9 package.
- mongodb

Still not available:
- xmlrpc

**Comment by stronk7** [comment]
For the records, I've asked @ https://github.com/php/pecl-networking-xmlrpc/issues/2 if there is going to be a new RCX release of the extension @ PECL or no.

We always can built it locally (vs from PECL), so tests continue working and so on...

... but it's becoming an absolute priority to get on [XMLRPC to be or not to be](https://tracker.moodle.org/browse/MDL-70889) ASAP. No matter the answer to the question.

Ciao :-)

**Comment by stronk7** [comment]
Yay, so now [php-xmlrpc 1.0.0RC3](https://pecl.php.net/package/xmlrpc) is available and that enables us to complete the PHP 8.1 images.

I'm going to add a comment @ https://tracker.moodle.org/browse/MDL-70889, because we need to seriously consider that issue before Moodle 4.1 (that will come with PHP 8.1 support, hopefully).

**Comment by stronk7** [comment]
Ok, so now the 8.1.0 images are built and published:

- DH: https://hub.docker.com/repository/docker/moodlehq/moodle-php-apache/tags
- GH: https://github.com/moodlehq/moodle-php-apache/pkgs/container/moodle-php-apache

I'm going to close this now, thanks!
