### ISSUE TITLE
Provide here the Moodle external test resources

### ISSUE THREAD

**Issue by scara** [moodlehq/moodle-php-apache#15]
To avoid using external resources, we should add here these external resources (https://github.com/moodlehq/moodle-exttests), and in https://github.com/moodlehq/moodle-docker the setting to use these local resources and not those from http://download.moodle.org/.
Details: https://docs.moodle.org/dev/PHPUnit#External_test_resources.

I'll be happy to provide the PRs, if approved.

**Comment by scara** [comment]
Update: https://tracker.moodle.org/browse/MDLSITE-5296 describes the creation of a docker image to host those external test artifacts (https://github.com/moodlehq/moodle-exttests-apache) via an improvement done to the current code, https://github.com/moodlehq/moodle-exttests/pull/13 (https://tracker.moodle.org/browse/MDLSITE-5297).

Guessing that we should close this issue and open a new one into https://github.com/moodlehq/moodle-docker to expose there the local availability of those artifacts.
@andrewnicols, @stronk7: thoughts?

TIA,
Matteo

**Comment by andrewnicols** [comment]
I've created a new Dockerfile on the existing moodlehq/moodle-exttests code repository and a new Docker automated build at https://hub.docker.com/r/moodlehq/moodle-exttests.

The new image will be available once https://github.com/moodlehq/moodle-exttests/pull/14 lands.

Once that is available, I will create a pull request against this repository.

**Comment by andrewnicols** [comment]
The new docker image has landed. I'll look to integrate it with this repository shortly.

**Comment by andrewnicols** [comment]
Closing and deferring to https://github.com/moodlehq/moodle-docker/issues/70
